name: "Entrega contínua"

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: cviniciussdias
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Constrói e envia imagem docker
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: cviniciussdias/projeto_go:latest,cviniciussdias/projeto_go:${{ github.sha }}

  deploy_to_ec2:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Build
        run: go build main.go

      - name: Unir arquivos
        run: tar -cvf build.tar ./assets ./templates ./main

      - name: SCP to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          source: "build.tar"
          target: /home/${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}

      - name: Extract build.tar and Restart service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            tar -xvf build.tar
            sudo systemctl restart projeto
