name: "Construção do artefato"

on:
  push:
    branches: [ "main", "curso_2" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build docker image
        run: docker build --target=production -t cviniciussdias/projeto_go:${{ github.sha }} .
